import type { EmbedThemePreset } from './types';

export const EMBED_THEME_PRESETS: EmbedThemePreset[] = [
  {
    id: 'success',
    name: 'Success',
    description: 'Green accent for confirmations',
    color: '#10B981',
    author: '',
    footer: 'Status: Completed',
    thumbnail: '',
    fields: [
      { name: 'Status', value: 'Completed successfully', inline: true },
      { name: 'Timestamp', value: '{{datetime}}', inline: true },
    ],
  },
  {
    id: 'error',
    name: 'Error',
    description: 'Red accent for failures',
    color: '#EF4444',
    author: '',
    footer: 'An error occurred',
    thumbnail: '',
    fields: [
      { name: 'Error Code', value: 'ERR_001', inline: true },
      { name: 'Timestamp', value: '{{datetime}}', inline: true },
    ],
  },
  {
    id: 'warning',
    name: 'Warning',
    description: 'Amber accent for alerts',
    color: '#F59E0B',
    author: '',
    footer: 'Please review this warning',
    thumbnail: '',
    fields: [
      { name: 'Severity', value: 'Medium', inline: true },
      { name: 'Timestamp', value: '{{datetime}}', inline: true },
    ],
  },
  {
    id: 'info',
    name: 'Info',
    description: 'Blue accent for announcements',
    color: '#3B82F6',
    author: '',
    footer: 'Informational message',
    thumbnail: '',
    fields: [
      { name: 'Category', value: 'Announcement', inline: true },
      { name: 'Date', value: '{{date}}', inline: true },
    ],
  },
  {
    id: 'gaming',
    name: 'Gaming',
    description: 'Orange accent for game events',
    color: '#F97316',
    author: 'Game Server',
    footer: 'Powered by KMA Tools',
    thumbnail: '',
    fields: [
      { name: 'Server', value: 'KMA #1', inline: true },
      { name: 'Players', value: '{{user_count}}', inline: true },
      { name: 'Map', value: 'TBD', inline: false },
    ],
  },
  {
    id: 'discord',
    name: 'Discord',
    description: 'Classic Discord blurple',
    color: '#5865F2',
    author: '',
    footer: 'Sent via KMA Tools',
    thumbnail: '',
    fields: [
      { name: 'Source', value: 'KMA Webhook', inline: true },
      { name: 'Timestamp', value: '{{datetime}}', inline: true },
    ],
  },
  {
    id: 'stream',
    name: 'Stream',
    description: 'Purple accent for live streams',
    color: '#8B5CF6',
    author: 'Stream Bot',
    footer: 'Watch now!',
    thumbnail: '',
    fields: [
      { name: 'Status', value: 'LIVE', inline: true },
      { name: 'Viewers', value: '{{user_count}}', inline: true },
    ],
  },
  {
    id: 'event',
    name: 'Event',
    description: 'Pink accent for events',
    color: '#EC4899',
    author: 'Event Manager',
    footer: 'Don\'t miss out!',
    thumbnail: '',
    fields: [
      { name: 'Date', value: '{{date}}', inline: true },
      { name: 'Time', value: '{{time}}', inline: true },
      { name: 'Location', value: 'Online', inline: false },
    ],
  },
];
